/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * employee_details.java
 *
 * Created on Jan 18, 2009, 12:36:21 PM
 */

package hms;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Sandeep kumar
 */
public class employee_details extends javax.swing.JFrame {
Connection con=null;
PreparedStatement ps=null;
ResultSet rs=null;
String emp_id=null;
String emp_name=null;
String dob=null;
String doj=null;
String address=null;
String mob_no=null;
String basic_salary=null;
String ta=null;
String da=null;
String hra=null;
String tax=null;
String total=null;
String dd1=null;
String mm1=null;
String yy2=null;
String dd2=null;
String mm3=null;
String yy1=null;
int mm2=0;
String month=null;
String vsid="";
String vsid1="";
    /** Creates new form employee_details */
    public employee_details() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this emp_id. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtemp_id = new javax.swing.JTextField();
        txtemp_name = new javax.swing.JTextField();
        txtmob = new javax.swing.JTextField();
        txtbs = new javax.swing.JTextField();
        txtta = new javax.swing.JTextField();
        txtda = new javax.swing.JTextField();
        txthra = new javax.swing.JTextField();
        txttax = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        cmbdd = new javax.swing.JComboBox();
        cmbmm = new javax.swing.JComboBox();
        cmbyy = new javax.swing.JComboBox();
        cmbdd1 = new javax.swing.JComboBox();
        cmbmm1 = new javax.swing.JComboBox();
        cmbyy1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadd = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        btnsave = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jPanel2.setBackground(new java.awt.Color(219, 154, 13));

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(219, 19, 56));
        jLabel1.setText("Employee Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(197, 244, 83));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Employee id");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Employee Name");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("DOB");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("DOJ");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Mobile No");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Basic Salary");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("TA");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("DA");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("HRA");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("TAX");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Total");

        txtta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttaActionPerformed(evt);
            }
        });

        txthra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthraActionPerformed(evt);
            }
        });

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        cmbdd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DD", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cmbmm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MM", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        cmbyy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YYYY", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", " " }));

        cmbdd1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DD", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cmbmm1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MM", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));

        cmbyy1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YYYY", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", " " }));

        txtadd.setColumns(20);
        txtadd.setRows(5);
        jScrollPane1.setViewportView(txtadd);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cmbdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttotal)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtta)
                                    .addComponent(txthra))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addGap(26, 26, 26))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txttax)
                                    .addComponent(txtda, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                            .addComponent(txtbs)
                            .addComponent(txtmob)
                            .addComponent(jScrollPane1)
                            .addComponent(txtemp_name)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cmbdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cmbmm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbyy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cmbmm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbyy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtemp_id))
                        .addGap(26, 26, 26))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtemp_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtemp_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbmm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbyy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbmm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbyy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtmob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(txtbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txtta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(txthra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(54, 163, 204));

        btnsave.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnsearch.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btncancel.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnclear))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsearch))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnupdate))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncancel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnclear))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnsearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndelete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling emp_id here:
}//GEN-LAST:event_txttotalActionPerformed

    private void txthraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthraActionPerformed
        // TODO add your handling emp_id here:
}//GEN-LAST:event_txthraActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling emp_id here:
        emp_id=txtemp_id.getText();
        emp_name=txtemp_name.getText();

        Object dd=cmbdd.getSelectedItem();
        Object mm=cmbmm.getSelectedItem();
        Object yy=cmbyy.getSelectedItem();
        dob=dd+"-"+mm+"-"+yy;
        Object dd1=cmbdd1.getSelectedItem();
        Object mm1=cmbmm1.getSelectedItem();
        Object yy1=cmbyy1.getSelectedItem();
        doj=dd1+"-"+mm1+"-"+yy1;
        address=txtadd.getText();
        mob_no=txtmob.getText();
        basic_salary=txtbs.getText();
        ta=txtta.getText();
        da=txtda.getText();

        hra=txthra.getText();
        tax=txttax.getText();
        total=txttotal.getText();

        if(!emp_id.equals(""))
        {
            try
            {
                con=connection.connect.conn();
                ps=con.prepareStatement("insert into employee_details values(?,?,?,?,?,?,?,?,?,?,?,?)");
                ps.setString(1,emp_id);
                ps.setString(2,emp_name);
                ps.setString(3,dob);
                ps.setString(4,doj);
                ps.setString(5,address);
                ps.setString(6,mob_no);
                ps.setString(7,basic_salary);
                ps.setString(8,ta);
                ps.setString(9,da);
                ps.setString(10,hra);
                ps.setString(11,tax);
                ps.setString(12,total);

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data has been inserted successfully");
                clear();
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Data has not been inserted!!");
        }

    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling emp_id here:
         dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling emp_id here:
        clear();
    }//GEN-LAST:event_btnclearActionPerformed

    private void txttaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttaActionPerformed
        // TODO add your handling emp_id here:
    }//GEN-LAST:event_txttaActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling emp_id here:
        emp_id=txtemp_id.getText();
        emp_name=txtemp_name.getText();

        Object dd=cmbdd.getSelectedItem();
        Object mm=cmbmm.getSelectedItem();
        Object yy=cmbyy.getSelectedItem();
        dob=dd+"-"+mm+"-"+yy;
        Object dd1=cmbdd1.getSelectedItem();
        Object mm1=cmbmm1.getSelectedItem();
        Object yy1=cmbyy1.getSelectedItem();
        doj=dd1+"-"+mm1+"-"+yy1;
        address=txtadd.getText();
        mob_no=txtmob.getText();
        basic_salary=txtbs.getText();
        ta=txtta.getText();
        da=txtda.getText();
        hra=txthra.getText();
        tax=txttax.getText();
        total=txttotal.getText();

       try
        {
            con=connection.connect.conn();
            ps=con.prepareStatement("update employee_details set emp_id=?,emp_name=?,dob=?,doj=?,address=?,mob=?,bs=?,ta=?,da=?,hra=?,tax=?,total=?");
            ps.setString(1,emp_id);
                ps.setString(2,emp_name);
                ps.setString(3,dob);
                ps.setString(4,doj);
                ps.setString(5,address);
                ps.setString(6,mob_no);
                ps.setString(7,basic_salary);
                ps.setString(8,ta);
                ps.setString(9,da);
                ps.setString(10,hra);
                ps.setString(11,tax);
                ps.setString(12,total);
      ps.executeUpdate();
      JOptionPane.showMessageDialog(null,"data has been edited");
        }
        catch(Exception e)
        {
          JOptionPane.showMessageDialog(null,"sorry data has not been edited");
        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling emp_id here:
        emp_id=txtemp_id.getText();
if(!emp_id.equals(""))
{
     try
        {
            con=connection.connect.conn();
            ps=con.prepareStatement("select * from employee_details where emp_id=?");
            ps.setString(1,emp_id);
            rs=ps.executeQuery();
            while(rs.next())
            {
             txtemp_id.setText(rs.getString(1));
             txtemp_name.setText(rs.getString(2));
             java.sql.Date dbSqlDate=null;
             dbSqlDate=rs.getDate(3);
             vsid= dbSqlDate.toString();

            JOptionPane.showMessageDialog(null,"date="+dbSqlDate);
            yy1=vsid.substring(0,4);
            mm1=vsid.substring(5, 7);
            dd1=vsid.substring(8);



JOptionPane.showMessageDialog(null,"yy="+yy1);
JOptionPane.showMessageDialog(null,"mm="+mm1);
JOptionPane.showMessageDialog(null,"dd="+dd1);
             cmbdd.setSelectedItem(dd1);
             mm2=mm1.compareTo("01");
             if(mm2==0)
            {
                month="Jan";
                 cmbmm.setSelectedIndex(0);
            JOptionPane.showMessageDialog(null,"mm="+month);

            }
             mm2=mm1.compareTo("02");
             if(mm2==0)
            {
                month="Feb";
                 cmbmm.setSelectedIndex(1);
            JOptionPane.showMessageDialog(null,"mm="+month);

            }

           mm2=mm1.compareTo("03");
             if(mm2==0)
            {
                month="Mar";
                 cmbmm.setSelectedIndex(2);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
            mm2=mm1.compareTo("04");
             if(mm2==0)
            {
                month="Apr";
                 cmbmm.setSelectedIndex(3);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
             mm2=mm1.compareTo("05");
             if(mm2==0)
            {
                month="May";
                 cmbmm.setSelectedIndex(4);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
              mm2=mm1.compareTo("06");
             if(mm2==0)
            {
                month="Jun";
                 cmbmm.setSelectedIndex(5);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
               mm2=mm1.compareTo("07");
             if(mm2==0)
            {
                month="Jul";
                 cmbmm.setSelectedIndex(6);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
            mm2=mm1.compareTo("08");
             if(mm2==0)
            {
                month="Aug";
                 cmbmm.setSelectedIndex(7);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
             mm2=mm1.compareTo("09");
             if(mm2==0)
            {
                month="Sep";
                 cmbmm.setSelectedIndex(8);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
              mm2=mm1.compareTo("10");
             if(mm2==0)
            {
                month="Oct";
                 cmbmm.setSelectedIndex(9);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
               mm2=mm1.compareTo("11");
             if(mm2==0)
            {
                month="Nov";
                 cmbmm.setSelectedIndex(10);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }

            mm2=mm1.compareTo("12");
             if(mm2==0)
            {
                month="Dec";
                 cmbmm.setSelectedIndex(11);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }

             cmbyy.setSelectedItem(yy1);
             java.sql.Date dbSqlDate1=null;
            dbSqlDate1=rs.getDate(4);
            vsid= dbSqlDate1.toString();

            JOptionPane.showMessageDialog(null,"date="+dbSqlDate1);
            yy2=vsid.substring(0,4);
            mm3=vsid.substring(5,7);
            dd2=vsid.substring(8);



JOptionPane.showMessageDialog(null,"yy="+yy2);
JOptionPane.showMessageDialog(null,"mm="+mm3);
JOptionPane.showMessageDialog(null,"dd="+dd2);
             cmbdd1.setSelectedItem(dd2);
             mm2=mm3.compareTo("01");
             if(mm2==0)
            {
                month="Jan";
                 cmbmm1.setSelectedIndex(0);
            JOptionPane.showMessageDialog(null,"mm="+month);

            }
             mm2=mm3.compareTo("02");
             if(mm2==0)
            {
                month="Feb";
                 cmbmm1.setSelectedIndex(1);
            JOptionPane.showMessageDialog(null,"mm="+month);

            }

           mm2=mm3.compareTo("03");
             if(mm2==0)
            {
                month="Mar";
                 cmbmm1.setSelectedIndex(2);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
            mm2=mm3.compareTo("04");
             if(mm2==0)
            {
                month="Apr";
                 cmbmm1.setSelectedIndex(3);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
             mm2=mm3.compareTo("05");
             if(mm2==0)
            {
                month="May";
                 cmbmm1.setSelectedIndex(4);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
              mm2=mm3.compareTo("06");
             if(mm2==0)
            {
                month="Jun";
                 cmbmm1.setSelectedIndex(5);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
               mm2=mm3.compareTo("07");
             if(mm2==0)
            {
                month="Jul";
                 cmbmm1.setSelectedIndex(6);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
            mm2=mm3.compareTo("08");
             if(mm2==0)
            {
                month="Aug";
                 cmbmm1.setSelectedIndex(7);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
             mm2=mm3.compareTo("09");
             if(mm2==0)
            {
                month="Sep";
                 cmbmm1.setSelectedIndex(8);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
              mm2=mm3.compareTo("10");
             if(mm2==0)
            {
                month="Oct";
                 cmbmm1.setSelectedIndex(9);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }
               mm2=mm3.compareTo("11");
             if(mm2==0)
            {
                month="Nov";
                 cmbmm1.setSelectedIndex(10);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }

            mm2=mm3.compareTo("12");
             if(mm2==0)
            {
                month="Dec";
                 cmbmm1.setSelectedIndex(11);
            JOptionPane.showMessageDialog(null,"mm="+month);
             }

             cmbyy1.setSelectedItem(yy2);
             txtadd.setText(rs.getString(5));
             txtmob.setText(rs.getString(6));
             txtbs.setText(rs.getString(7));
             txtta.setText(rs.getString(8));
             txtda.setText(rs.getString(9));
             txthra.setText(rs.getString(10));
             txttax.setText(rs.getString(11));
             txttotal.setText(rs.getString(12));

            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Sorry!\n No match found!");
        }
        }
    else
    {
        JOptionPane.showMessageDialog(null,"please enter the employee emp_id!!");
    }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
                emp_id=txtemp_id.getText();
        if(!emp_id.equals(""))
{
    try
    {
        con=connection.connect.conn();
 int ok=3;
        if(ok<=3)
        {
  int aa=JOptionPane.showConfirmDialog(null,"DO YOU WANT TO DELETE RECORDS");
             if(aa==JOptionPane.YES_OPTION)
        {
        ps=con.prepareStatement("delete from employee_details where emp_id=?");
        ps.setString(1,emp_id);
        ps.executeUpdate();


           JOptionPane.showMessageDialog(null, "DATA DELETED SUCCESSFULLY");
              clear();
        }
        else
        {
            if(aa==JOptionPane.NO_OPTION)
            JOptionPane.showMessageDialog(null," DATA NOT DELETED");
        }
        }
        else
        {
            dispose();
        }

    }
    catch(Exception e)
    {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null,"DATA HAS NOT BEEN DELETED");
    }
}
else

{
    JOptionPane.showMessageDialog(null,"Please enter the Employee Code for Delete Record!!");
}

    }//GEN-LAST:event_btndeleteActionPerformed

    /**
    * @param args the command line arguments
    */
    public void clear()
{
    txtemp_id.setText("");
    txtemp_name.setText("");

    cmbdd.setSelectedIndex(0);
    cmbmm.setSelectedIndex(0);
    cmbyy.setSelectedIndex(0);
    cmbdd1.setSelectedIndex(0);
    cmbmm1.setSelectedIndex(0);
    cmbyy1.setSelectedIndex(0);
    txtadd.setText("");
    txtmob.setText("");
    txtbs.setText("");
    txtta.setText("");
    txtda.setText("");

    txthra.setText("");
    txttax.setText("");
    txttotal.setText("");

}
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox cmbdd;
    private javax.swing.JComboBox cmbdd1;
    private javax.swing.JComboBox cmbmm;
    private javax.swing.JComboBox cmbmm1;
    private javax.swing.JComboBox cmbyy;
    private javax.swing.JComboBox cmbyy1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtadd;
    private javax.swing.JTextField txtbs;
    private javax.swing.JTextField txtda;
    private javax.swing.JTextField txtemp_id;
    private javax.swing.JTextField txtemp_name;
    private javax.swing.JTextField txthra;
    private javax.swing.JTextField txtmob;
    private javax.swing.JTextField txtta;
    private javax.swing.JTextField txttax;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

}
